### ISSUE TITLE
Automatic generation of contributor graphic in README.md

### ISSUE THREAD

**Issue by mttrbrts** [accordproject/techdocs#100]
**Is your feature request related to a problem? Please describe.**
Currently the contributor graphic that shows profile images for contributors in README.md is manually created.

**Describe the solution you'd like**
It would be awesome if this was created automatically during the Travis build for the master branch.

**Describe alternatives you've considered**
Currently [`scripts/get_contributors.sh`](https://github.com/accordproject/techdocs/blob/master/scripts/get_contributors.sh) uses the GitHub API to generate a Markdown file. This file is then rendered as HTML and converted to a PNG.

I'm open to other alternatives pipelines, including third-party services.

**Additional context**
PR that added the contributor graphic https://github.com/accordproject/techdocs/pull/98

**Comment by Niladri24dutta** [comment]
@mttrbrts is there any existing .yml file for travis CI that is being used for the master branch? if not then should I create a build definition for travis that executes the script scripts/get_contributors.sh ?

**Comment by mttrbrts** [comment]
Thanks @Niladri24dutta My mistake, I forgot that for this repo the contents of `website` is also built manually.

I suggest focussing on the image generate part, for now? I can set up the Travis skelton build tomorrow..

**Comment by kharaone** [comment]
There's actually an easy way through a bot for example which allows you a bit more of control than just adding a contributor automatically. I saw it used in different other repositories.
https://allcontributors.org/
I think that's something that would fit your current processes and is customizable enough to adapt for any changes. Everyone isn't contributing the same way ;)

**Comment by mttrbrts** [comment]
Great idea @kharaone, I've added the bot.

@all-contributors please add @kharaone, @Niladri24dutta for documentation

**Comment by mttrbrts** [comment]
Great idea @kharaone! I've added the bot.

@all-contributors please add @kharaone and @Niladri24dutta for documentation

**Comment by mttrbrts** [comment]
@Niladri24dutta perhaps you could modify the `scripts/get_contributors.sh` script to produce something similar to the old static image https://github.com/accordproject/techdocs/blob/master/assets/contributors.png but instead using the all-contributors JSON format in `.all-contributorsrc`? The bot will automatically generate the Markdown

See this PR by the bot for reference
https://github.com/accordproject/techdocs/pull/110/files

**Comment by Niladri24dutta** [comment]
@mttrbrts Can you let me know where should I use the cli command `all-contributors generate`? Do i need to create the file `.all-contributorsrc` manually?

**Comment by mttrbrts** [comment]
> @mttrbrts Can you let me know where should I use the cli command `all-contributors generate`? Do i need to create the file `.all-contributorsrc` manually?

It looks like you should start with `all-contributora init` https://allcontributors.org/docs/en/cli/usage#all-contributors-init

**Comment by daniloff200** [comment]
Yes, `all-contributors init` generates the `.all-contributorsrc` file, but, it's empty, and you have to add all users, who contributed with `add ` command.

Looks actually weird
For example, for this repo 
`jeromesimeon, dselman, mttrbrts, irmerk, peterhunn, javiercanossini, lex111, 4katie, FelixKuehl, 4dd3r, daniloff200, jbesq777, Michael-Grover, nithilan4, oorjitchowdhary, contractpendev, pranjalv9, ryanctlin, Yash-Garg `  

is a full list of contributors, and I have to add each of them...

**Comment by daniloff200** [comment]
Same with the bot
You can add only one user per request to the bot, he will pick the first one and make a PR

**Comment by mttrbrts** [comment]
Thanks for the update @daniloff200 , that's frustrating 🤔

Does the `check` function in the CLI help?

**Comment by daniloff200** [comment]
Actually, this list of contributions, that I shared above, was the result of `check`
It doesn't update the list of contributors, it just compares the actual list on Github, and your local `all-contributorsrc`.

**Comment by kharaone** [comment]
The initial commit will probably require a simple seeding setup 
init-command
foreach contributor from check-command
   add-command contributor
generate-command

and then the bot (or cli) can take care of the updates.

**Comment by Niladri24dutta** [comment]
> 
> 
> Actually, this list of contributions, that I shared above, was the result of `check`
> It doesn't update the list of contributors, it just compares the actual list on Github, and your local `all-contributorsrc` @mttrbrts

Yes it taking a lot of manual effort to put each name in the list.

**Comment by mttrbrts** [comment]
I like @kharaone's plan. @daniloff200 , are you happy to give that a go?

It seems like we have all of the components, between the all-contributors CLI, bit and my bash script.

**Comment by daniloff200** [comment]
sounds good for me @mttrbrts 
But, I don't exactly get, how we gonna execute all the steps, mentioned by @kharaone ,  so, just waiting from some example solution for this repo

**Comment by kharaone** [comment]
You should have an example of what I meant by seeding the initial run. #162

**Comment by irmerk** [comment]
Want to make sure I understand what #162 does now: There is now a script in this repo that we can manually run to regenerate the list of contributors, correct?

**Comment by kharaone** [comment]
The initial point was to provide an initialisation script for the configuration file. 
If you already have a configuration file, it will indeed update it with contributors it didn't have.

**Comment by irmerk** [comment]
So I believe we'd want this issue to now track the implementation of the same concept in the following repos: 

- [ ] `ergo`
- [ ] `cicero`
- [ ] `concerto`
- [ ] `markdown-transform`
- [ ] `markdown-editor`
- [ ] `cicero-ui`
- [ ] `concerto-ui`
- [ ] `template-studio-v2`
- [ ] `cicero-vscode-extension`
- [ ] `cicero-template-library`
- [ ] `models`
- [x] `techdocs`(@kharaone)

**Comment by jeromesimeon** [comment]
I'll voice a bit of a contrarian opinion on this. I'm not sure why we need to add all this extra work for something GitHub handles perfectly well already. GitHub also does this process without polluting the build process or the PRs.

**Comment by irmerk** [comment]
Open to this issue and #83 being focused into the `techdocs` itself for a specific section, because it's a good point to not necessarily have this in the source code for libraries.

**Comment by kharaone** [comment]
the upstream PR have been approved too, which means that the readme.md file will need the comment-marker for the badge section too to get the bot working accordingly.

**Comment by irmerk** [comment]
Scratch https://github.com/accordproject/techdocs/issues/100#issuecomment-544139519, this issue is closed.
