### ISSUE TITLE
Accord Project logo in the nav bar is not the correct logo

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/techdocs#106]
The Accord Project text in the nav bar is not the actual Accord Project logo. See the footer for the proper logo:

![image](https://user-images.githubusercontent.com/40569793/66080244-b38d8580-e533-11e9-9644-cac8cfcd3062.png)

Here is the SVG file of the proper logo

[A-MARK-ACCORDPROJECT-ONELINE-white.svg.zip](https://github.com/accordproject/techdocs/files/3683242/A-MARK-ACCORDPROJECT-ONELINE-white.svg.zip)

@irmerk please add labels to this when you have a chance. I don't have permission to.

**Comment by Frozenaught** [comment]
Hi, if no one is working on this issue I would be keen to do it.

**Comment by Michael-Grover** [comment]
@Frozenaught thanks for taking this on. I'm going to close this issue now 👍
