### ISSUE TITLE
Improve Information Architecture

### ISSUE THREAD

**Issue by dselman** [accordproject/techdocs#111]
A top-down review of how we organise the information in the documentation and who it is for.

This is becoming more pressing as we work on the documentation for Cicero v0.20 with the new CiceroMark markup, as well as folding in the documentation for Concerto.

Related issues:
#108 
#96 
#91 

Straw man proposal:
https://docs.google.com/spreadsheets/d/1YaGFm6t0Y__tzdG_N6fUCG5EvjdeiffpB3JMdKR-zA0/edit#gid=0

**Comment by gabrielgene** [comment]
Hi @dselman
How can I help here?
You want to make the documentation structure the same as the spreadsheet?

The overview section is this?
![image](https://user-images.githubusercontent.com/19671668/67153237-f2556680-f2bb-11e9-86de-f634b69cc95d.png)
![image](https://user-images.githubusercontent.com/19671668/67153249-1e70e780-f2bc-11e9-8cc9-76e30619186b.png)

I can do this ;)

**Comment by dselman** [comment]
There have been good improvements already. We will discuss and review at the next Tech WG call, Wed 4pm EST. You are welcome to join!

**Comment by jeromesimeon** [comment]
I really like some of the suggested reorganisations. I have a couple of suggestions though with the following goals:
- For the "developer in a rush", a section that would get someone started in 15 minutes tops
- More clearly separate tutorials from technical material
- Increase the visibility for the key syntax guides: Markup guide, Concerto guide, Ergo guide which are fundamental for anyone who wants to _author_ templates

I've put those ideas into a similarly-shaped spreadsheet here:
https://docs.google.com/spreadsheets/d/1oEKG6T1qZWhSkWO_X3wbm6B3Q56DoCoGrHV-Y489SLs/edit#gid=0

**Comment by jeromesimeon** [comment]
@dselman @4katie @peterhunn @irmerk Has this been addressed by the latest reorganisation of the documentation, or should we leave this open and do another round?

**Comment by dselman** [comment]
Happy to close. You win this round!

**Comment by jeromesimeon** [comment]
I'd like to see this as a happy compromise between best and good! Closing this issue.
