### ISSUE TITLE
Slack button leads to wrong place 

### ISSUE THREAD

**Issue by daniloff200** [accordproject/techdocs#121]
**Describe the bug**
Wrong URL in Slack button on the main page

**To Reproduce**
1. Go to https://docs.accordproject.org/
2. Click on Slack button
3. You will be redirected to some Google form, and, you need permission here (probably, if you're logged in as an member of owner organisation, you will not see it)

**Expected behavior**
User should be redirected to the Slack invitation (Probably,    [here](https://accord-project-slack-signup.herokuapp.com/)  )

**Additional context**
Perhaps, I wrong here, but, im my opinion, link should be fixed, or, button should be renamed

**Comment by daniloff200** [comment]
Oh, another interesting place

In footer there's also link to slack, and it's `https://accord-project.slack.com/messages/C7U521CTG` which also looks strange, because, if I don't have access to Accord Slack workspace, I will be initially redirected here `https://accord-project.slack.com/?redir=%2Fmessages%2FC7U521CTG`

Perhaps, that also should be updated ?

Any thoughts @irmerk ?

**Comment by irmerk** [comment]
Wow, I'm surprised we haven't caught this one yet! Yes, the link should be `https://accord-project-slack-signup.herokuapp.com/` for both of these buttons.
