### ISSUE TITLE
AP version number overlaps search bar

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/techdocs#153]
**Describe the bug**
In the nav bar, the Accord Project logo and version number overlaps the search bar on narrow screen widths (mobile)

**To Reproduce**
1. Go to docs.accordproject.org on a mobile device, or reduce your window screen width to below 500px

**Expected behavior**
We expect the search bar to be accessible at all screen widths.

**Suggested fix**
At screen widths less than 600px, remove the "ACCORD PROJECT" Text from the Accord Project logo so that just the icon is there.

Set the Alt text to "Return to docs.accordproject.org homepage"

[Accord-Project-logo-small.svg.zip](https://github.com/accordproject/techdocs/files/3707997/Accord-Project-logo-small.svg.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/40569793/66492007-afa4ba80-ea81-11e9-9a82-1b96041b94d4.png)

**Comment by shahsank3t** [comment]
Is someone working on this issue? Else I would like to start on it

**Comment by Michael-Grover** [comment]
@shahsank3t no one is currently working on this issue. Feel free to take it.

Thanks!

**Comment by jeromesimeon** [comment]
I think this might be a Docusaurus issue. I would see if this has been fixed in more recent versions before doing anything on the source in this repo. One possibly related issue is https://github.com/facebook/docusaurus/issues/1697

**Comment by jeromesimeon** [comment]
> @shahsank3t I think this might be a Docusaurus issue. I would see if this has been fixed in more recent versions before doing anything on the source in this repo. One possibly related issue is [facebook/docusaurus#1697](https://github.com/facebook/docusaurus/issues/1697)

Maybe I'm wrong, since we're using an image...

**Comment by shahsank3t** [comment]
@jeromesimeon - Yes, since we are using an image (logo + text) we are running into this issue. Instead if similar to what Docusaurus does, if we using the small logo and the text separately, Docusaurus will take care of hiding the text when screen size gets smaller.

**Comment by shahsank3t** [comment]
@Michael-Grover @jeromesimeon - Created PR - https://github.com/accordproject/techdocs/pull/158

**Comment by irmerk** [comment]
@Michael-Grover this is closed, correct?
