### ISSUE TITLE
Typo in DEVELOPERS.md

### ISSUE THREAD

**Issue by shahsank3t** [accordproject/techdocs#154]
**Describe the bug**
In DEVELOPERS.md ([here](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#building-a-project)), URL of the main repository to be added as upstream has a typo in it. `acccordproject` should be `accordproject`

**To Reproduce**
1. Go to [DEVELOPERS.md](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#building-a-project)
2. Check 'Add the main repository as an upstream remote to your repository'
3. Notice the typo in URL

**Expected behavior**
Instead of `acccordproject`, it should be `accordproject`

**Comment by shahsank3t** [comment]
@Michael-Grover - can you please add some labels to this and assign it to me so I could quickly open a PR for this?

**Comment by Michael-Grover** [comment]
@shahsank3t done, thank you for finding this issue

**Comment by shahsank3t** [comment]
Pull Request: https://github.com/accordproject/techdocs/pull/155
