### ISSUE TITLE
Missed a step for Building a Project in DEVELOPERS.md 

### ISSUE THREAD

**Issue by shahsank3t** [accordproject/techdocs#156]
**Describe the bug**
Before installing node.js dependencies, one must need to navigate into `website` directory first which is not documented in DEVELOPERS.md

**To Reproduce**
1. Go to [DEVELOPERS.md](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#building-a-project)
2. After executing first three commands mentioned, on executing the forth command `npm install` it fails to find package.json file

**Expected behavior**
Step to navigate to `website` directory should be added in the doc

**Comment by shahsank3t** [comment]
@Michael-Grover - another bug found in DEVELOPERS.md

**Comment by Michael-Grover** [comment]
@irmerk or @jeromesimeon could assess and tag this more accurately than me

**Comment by irmerk** [comment]
@jeromesimeon I'm not 100% but this sounds true for this repository.

**Comment by rei2hu** [comment]
I'd like to fix this, but like irmerk said, this problem is only relevant for this repository; it appears that all of the other Accord repositories have a package.json in their root directory.

**Comment by VishalS99** [comment]
I have taken up this small problem and given a PR. Could it be reviewed?

**Comment by Michael-Grover** [comment]
@VishalS99 Thank you for taking up the issue. Can you link the PR in this comment thread when you have a chance?

**Comment by VishalS99** [comment]
Can someone check it up?

**Comment by irmerk** [comment]
Thanks @VishalS99 

Yes @rei2hu, I believe this is only the case in this repo.
