### ISSUE TITLE
advanced-latedelivery.md: Buyer and Seller must be swapped

### ISSUE THREAD

**Issue by 4katie** [accordproject/techdocs#171]
**Is your feature request related to a problem? Please describe.**
'Buyer' and 'Seller' in this documentation must be swapped (seller must pay buyer, not the other way around) 

**Describe the solution you'd like**
As above - both in the text and in the image files

**Describe alternatives you've considered**
N/A

**Additional context**
Potentially linked to [Cicero Template Library Issue #259](https://github.com/accordproject/cicero-template-library/issues/259 )

**Comment by Innovator007** [comment]
I would like to work on this please assign it to me

**Comment by rmoswela** [comment]
I will try this one :-)

**Comment by Innovator007** [comment]
Hi @irmerk i have added a pull request [here](https://github.com/accordproject/techdocs/pull/173), can you review it please :)

**Comment by daniloff200** [comment]
is it really a medium one?
Maybe, there's something more, then one line fix?

**Comment by irmerk** [comment]
> is it really a medium one?
> Maybe, there's something more, then one line fix?

I was on too much of a roll this morning and thought this was in `cicero-template-library`, not the docs.

**Comment by daniloff200** [comment]
@irmerk  actually, me too,  despite it's 5 PM for me :D

This task requires not only two line changes (which actually easy to make), but also, whole new screenshots, because of the changes in code of template . So, I assume, it can be Medium

**Comment by irmerk** [comment]
If someone could take on the screenshots work @daniloff200 left off on from #176, that work is open.

**Comment by doomswatter** [comment]
I was going to work on this, but when I attempted to load the template from the link in the documentation, I got the error shown in the attached screenshot. I'm not sure what to do about it. Should I create another issue?
![Template_Error](https://user-images.githubusercontent.com/44559839/67050800-68649c80-f107-11e9-966f-4c268dd7038d.PNG)

**Comment by irmerk** [comment]
@doomswatter it looks like you're loading a version of a template that isn't supported into template studio. @jeromesimeon what version is supported currently?

**Comment by jeromesimeon** [comment]
@irmerk see "Help > About"

**Comment by jeromesimeon** [comment]
@doomswatter fixing the link is probably a good place to start! You can find the latest version of all the templates here: https://templates.accordproject.org

**Comment by doomswatter** [comment]
I'll do that. Thanks!

**Comment by doomswatter** [comment]
Oops, I used the wrong link. I'll fix it.

**Comment by doomswatter** [comment]
I'm sorry, I'm new at this. I have new screenshots with the relevant changes, but I'm not sure how to go about using them in an edit for a pull request. Googling around for the answer didn't help me.

**Comment by doomswatter** [comment]
Okay, I uploaded the new screenshots with a pull request. They have the same names as the originals, so they should work fine with the current code.

**Comment by doomswatter** [comment]
I have the new screenshots ready, but I'm not sure how to submit them to you through a pull request, as I'm not allowed to upload into assets. I'm new to this, so I'm sure I'm just ignorant. Any help is greatly appreciated.

**Comment by irmerk** [comment]
@doomswatter you should be able to just replace this image files in your local repo, and when you push up and create a PR it will be a PR to replace the image files.

**Comment by doomswatter** [comment]
Thanks! That should do it!

**Comment by daniloff200** [comment]
Correct me, If I wrong, but,  it should be closed, right? 
cc @irmerk

**Comment by irmerk** [comment]
Should close on resolution of https://github.com/accordproject/cicero-template-library/pull/281
