### ISSUE TITLE
accordproject-studio.md: Broken image

### ISSUE THREAD

**Issue by fr1sk** [accordproject/techdocs#178]
Image `studio.png` is broken inside `accordproject-studio.md` doc file

**Comment by fr1sk** [comment]
I will be on it

**Comment by fr1sk** [comment]
fixed

**Comment by jeromesimeon** [comment]
@fr1sk I am a bit confused by this issue. I _think_ that page is obsolete and not actually built as part of the Web site. Could you provide a snapshot of the issue from the documentation site itself?

**Comment by fr1sk** [comment]
![image](https://user-images.githubusercontent.com/15851195/66942547-9f747880-f049-11e9-9b07-ee2f495d7e7c.png)
@jeromesimeon

**Comment by jeromesimeon** [comment]
@fr1sk I meant in the Web site: https://docs.accordproject.org

**Comment by irmerk** [comment]
Same as @jeromesimeon, I'm not sure where the issue is or how #179 is fixing it.

**Comment by jeromesimeon** [comment]
I still don't think this is an issue. I'm closing this.
