### ISSUE TITLE
Avoid 'simply' and 'just'

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#184]
We should scan through our docs to replace or omit words such as 'simply' or 'just'.

**Comment by matthew-was** [comment]
I was just doing a pr for react-native which uses https://alexjs.com/ to fix issues like these. I've never really used it but would be interested in integrating it here as a chance to learn and fix this issue at the same time.

**Comment by CryoZEUS** [comment]
Can I take this one? I've sorta 
started working on it already.

**Comment by irmerk** [comment]
Sure @CryoZEUS, there are already working changes in #185

**Comment by CryoZEUS** [comment]
Thank you. 
I'm kinda new over here, but I'm keen on helping out whatever way I can.

**Comment by doomswatter** [comment]
I've scoured everything in techdocs/docs/ and made helpful changes. There were several superfluous instances of "simply" remaining, but I have obliterated them in the hopes of closing out this issue.

**Comment by irmerk** [comment]
@doomswatter great, you can put a PR in!

**Comment by karandixit10** [comment]
I would like to work on this issue

**Comment by whitehawk0011** [comment]
Is this done or can I hop into it?

**Comment by snehit31** [comment]
I wanted to contribute in solving this issue,if it is still available?

**Comment by chauxvive** [comment]
I'd like to work on this too, if it's not finished yet please.

**Comment by whitehawk0011** [comment]
I have done a pull request, please check!

**Comment by snehit31** [comment]
Help me with this error
You have 2 commits incorrectly signed off. To fix, head to your local branch and run:

git rebase HEAD~2 --signoff
Now your commits will have your sign off. Next run

git push --force-with-lease origin patch-3

**Comment by irmerk** [comment]
@snehit31 might try `-f` instead of `--force-with-lease`

**Comment by RobbiNespu** [comment]
Hi @irmerk , firstly nice documentation you have there. 
I do some changes by omit or replace the 'simply' wording. Could you check and review? Thanks

**Comment by whitehawk0011** [comment]
These changes have been made in https://github.com/accordproject/techdocs/pull/219#event-2741706200

**Comment by irmerk** [comment]
Closing, #217 is still outstanding.
