### ISSUE TITLE
Improper word choice as well as Improper formatting in ReadMe.md

### ISSUE THREAD

**Issue by gargarchit** [accordproject/techdocs#226]
I found some Improper word choice as well as Improper formatting for that I have made changes and corrected that so, now It will be easier for everyone to read. 
in pr https://github.com/accordproject/cicero-ui/pull/195

We need to change this in all

**Comment by gargarchit** [comment]
Also in https://github.com/accordproject/markdown-transform/pull/97

**Comment by gargarchit** [comment]
Also in https://github.com/accordproject/ergo/pull/692

**Comment by gargarchit** [comment]
Also in https://github.com/accordproject/ergo/pull/692 , 
https://github.com/accordproject/concerto/pull/145 , 
https://github.com/accordproject/markdown-transform/pull/97

**Comment by gargarchit** [comment]
https://github.com/accordproject/cicero-template-library/pull/295

**Comment by irmerk** [comment]
Let me know when you have a PR in for all main repos and we can review all at once.

**Comment by gargarchit** [comment]
@irmerk I think I have done for major repos listed 
Please let me know any other Repos for correcting it's README

**Comment by irmerk** [comment]
Docs for the following repos need to be consistent, so I don't want to be reviewing piece meal PRs, rather all of them at once to keep consistent:

- `markdown-transform`
- `ergo`
- `cicero`
- `concerto`
- `markdown-editor`
- `cicero-ui`
- `cicero-template-library`
- `models`
- `techdocs`
- `cicero-vscode-extension`
- `slack-app`
- `concerto-ui`
- `template-studio-v2`

**Comment by gargarchit** [comment]
Okay @irmerk I will do for all

**Comment by gargarchit** [comment]
Progress:

|Repo Name|README.md|DEVELOPERS.md|
|---------|-------|-------|
|markdown-transform|Done|Done|
|ergo||Done|
|cicero|||
|concerto|||
| markdown-editor|||
|cicero-ui|||
|cicero-template-library|Done|Done|
|models|||
|techdocs|||
|cicero-vscode-extension|||
|slack-app|||
|concerto-ui|||
|template-studio-v2|||

**Comment by gargarchit** [comment]
@irmerk I have updated all the repos Please merge
