### ISSUE TITLE
Code text is too low contrast

### ISSUE THREAD

**Issue by Michael-Grover** [accordproject/techdocs#233]
Short code text is too low contrast. (when there’s a light gray box around monospaced text) When text is on a gray background, make the text this color: #15203C.

example of text that is too low contrast:
![image](https://user-images.githubusercontent.com/40569793/67721013-e2204400-f9ab-11e9-9797-e43c6a7813e3.png)

**Comment by m4tr1k** [comment]
@Michael-Grover can I take this one?

**Comment by Michael-Grover** [comment]
@m4tr1k yes, thank you!

**Comment by Michael-Grover** [comment]
thanks @m4tr1k
