### ISSUE TITLE
Description for Cicero engine in ecosystem table should use "Accord Project"

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/techdocs#236]
Besides the typo, I believe we should _not_ use "Accord Protocol" anymore but "Accord Project". Also I don't believe we have a template specification anymore.

<img width="996" alt="Screenshot 2019-10-29 at 9 49 52 AM" src="https://user-images.githubusercontent.com/670099/67773173-af209380-fa31-11e9-8ab7-93053a7d5db1.png">

Whichever description text we decide on, this should be fix in every project which includes the ecosystem table.

**Comment by jeromesimeon** [comment]
Flagging @peterhunn and @irmerk on this.

**Comment by PseudoNerd** [comment]
Is modification necessary for this particular instance or for every instance of the usage ? 

If this is still open, I'd like to take this up.

**Comment by jeromesimeon** [comment]
> Is modification necessary for this particular instance or for every instance of the usage ?
> 
> If this is still open, I'd like to take this up.

Thanks @PseudoNerd 

Actually, this looks fixed here https://github.com/accordproject/techdocs#core-libraries

But not in other projects e.g., https://github.com/accordproject/cicero#core-libraries

If you are interested to fix those, I'll definitely assign you.

**Comment by PseudoNerd** [comment]
Yes @jeromesimeon , I could take them up.

**Comment by PseudoNerd** [comment]
I have made a PR on the Cicero repo.

**Comment by irmerk** [comment]
Will this be closed by https://github.com/accordproject/cicero/pull/592 @jeromesimeon?

**Comment by jeromesimeon** [comment]
> Will this be closed by [accordproject/cicero#592](https://github.com/accordproject/cicero/pull/592) @jeromesimeon?

I doubt it. I'm suspecting this issue is in every other repo.

**Comment by irmerk** [comment]
We can revert out that table that was put in last October. It may have been the wrong direction.

**Comment by irmerk** [comment]
Resolved with https://github.com/accordproject/cicero/pull/631
