### ISSUE TITLE
Author Docs for Unsupported Templates

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#260]
**Is your feature request related to a problem? Please describe.**
Template authors need to be notified that certain Cicero v0.20 features are not yet supported in the UI:
- variable lists
- nested lists
- conditionals
- code blocks

**Describe the solution you'd like**
documentation for template authors + “oops” message when adding a template would hopefully mitigate the issues users may face

**Additional context**
Related to [`cicero-ui` #237](https://github.com/accordproject/cicero-ui/issues/237)

**Comment by dselman** [comment]
Added docs:
https://github.com/accordproject/techdocs/commit/9b912a436bf12eceb718a255fbf23aaf34a32b1d
