### ISSUE TITLE
Hacktoberfest Post-Mortem 

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#265]
Tracking information to compile into a wiki article for future reference on Hacktoberfest participation. Feel free to add your thoughts! 

Tagging @Michael-Grover @mttrbrts @jeromesimeon @dselman @DianaLease @peterhunn

**Comment by Michael-Grover** [comment]
- We could consider putting a limit on shirts we send, i.e. "First 25 people to contribute 4 PRs get a free Accord Project shirt!" or "25 most significant contributions get a free shirt!" so we can control how much we spend on shirts
 - Have a video explaining DCO sign-off to make it very clear for unexperienced github and terminal users

**Comment by jeromesimeon** [comment]
@irmerk Can we close this?
