### ISSUE TITLE
Incorrect Concerto-core version under API tutorial 

### ISSUE THREAD

**Issue by adrijshikhar** [accordproject/techdocs#282]
**Describe the bug**
The npm package version specified in the docs to download `concerto-core` to use API, shows an error. NPM says that particular version not found. So can we change it latest one , ie, `0.82.7` ?

**To Reproduce**
1. Go to https://docs.accordproject.org/docs/model-api.html
2. Run the npm command specified.
3. See error

**Expected behavior**
It should install the specified version.

**Screenshots**
![Screenshot_20200322_001937](https://user-images.githubusercontent.com/41939219/77234275-0a1a7900-6bd3-11ea-92cd-e1a3d4df438e.png)

**Comment by adrijshikhar** [comment]
@jeromesimeon If we remove the specified version in the command and change it from `npm install @accordproject/concerto-core@0.20 --save` to `npm install @accordproject/concerto-core --save`, it works. One more thing, will the updated version create any problem with other documentation?

**Comment by jeromesimeon** [comment]
> @jeromesimeon If we remove the specified version in the command and change it from `npm install @accordproject/concerto-core@0.20 --save` to `npm install @accordproject/concerto-core --save`, it works. One more thing, will the updated version create any problem with other documentation?

This is just a bug. As far as I know there never was a `0.20` version. It's most likely a copy-paste from the Cicero version.

Either the most recent version or no-version would work! @adrijshikhar Will you do a PR?

**Comment by adrijshikhar** [comment]
Yes sure, i will fix this. Thanks.
