### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/techdocs#297]
It would be great to add a "Frequently Asked Questions" section to the documentation.

Please list suggestions for what it should contain (or questions that actually are asked frequently!) to this issue.

**Comment by jeromesimeon** [comment]
There is a FAQ here: https://www.accordproject.org/frequently-asked-questions/

So maybe we don't need anything else?

@Michael-Grover @irmerk

**Comment by irmerk** [comment]
I think we should consolidate and create further sections... For example: **AP**, **Smart Contracts**, **Cicero**, **Ergo**, etc.
This might be better suited to be handled in the documentation site.

As @Michael-Grover had mentioned, the main AP site does not support FAQ categories, so this could be an argument for handling in the documentation.

**Comment by tbrooke** [comment]
I scanned through the docs again and looked at FAQs for some other projects to get a feel for them, some seemed to use them for a catchall for things that don't fit anywhere else, some used them to differentiate their project from others, some used them as pointers back into the documentation. Some had small sections others had large sections.

It is in the overview but I can see separate  FAQs for Lawyers and for Developers and then separate FAQs based on categories. 

The amount of detail is a balance between FAQ and Regular Docs and in  alot of instances the FAQ may just refer back to the Documentation -- 

It also might be nice to review Slack questions, and talk with users and potential users

Maybe another box after Reference Manual called FAQs 

**Lawyers:**

* My contracts are in Word how can I get them to Accord?
* I've heard of Ethereum/Solidity smart contracts how is Accord different?
* How and where do I run my Accord contract?
* I don't like any of the templates can I create my own?
* Can I create a template library for my firm?

**Developers:**

* Can I edit Accord code with my favorite editor, VSCode?
* What can I do from the command line with Accord?
* How can I integrate Accord with my React project? Are there any components or examples?
* How can I convert a Concerto model to json?
* How do I use Accord in my project?
* How do I use the Accord API?
* Can Accord interact with my CRM, practice management or data management system?

Then maybe switch gears to general topics
Ergo
Cicero
etc.

**Comment by tbrooke** [comment]
My thoughts after attempting my FAQ Section is to **Not** have a separate top Level faq but rather expand the introduction and add a "For Lawyers" section along with the existing For Business and For Developers - The existing faq seems OK and could be added to mayb more of a newsy think than a doc thing - What does anybody think?

**Comment by irmerk** [comment]
I think the [existing FAQ](https://www.accordproject.org/frequently-asked-questions/) should be removed or just point to the docs [Introduction](https://docs.accordproject.org/docs/accordproject.html) or [Reference Manual](https://docs.accordproject.org/docs/ref-glossary.html), which would have a FAQ section. Each subsection of the Introduction having it's own form of FAQ seems more disjointed. I think it would be more thorough to have _For Business_, _For Developers_, _For Lawyers_, and _FAQ_.

**Comment by tbrooke** [comment]
I like that - so the Introduction section would have; Overview, Key Concepts, For Business, For Lawyers, For Developers and FAQ with eveything coordinated so it doesn't overlap -- I see the FAQ section as pretty small and maybe more dynamic to respond to real questions from real people as they work with Accord Project
