### ISSUE TITLE
Transmute ⚗️ (v0.21)

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#298]
# Transmute ⚗️ 
Tracking the updates to documentation around the new parser

## Tasks
- [ ] **Release Notes**
  - [ ] Ergo
    - [ ] Benchmark improvements?
  - [ ] Cicero
    - [ ] Benchmark improvements?
  - [ ] Markdown Transform
    - [ ] Benchmark improvements?
  - [ ] Web Components
- [ ] **Update screenshots**
- [ ] **Syntax**
  - [ ] Clause Template
  - [ ] CiceroMark DOM
  - [ ] TemplateMark DOM
  - [ ] Slate DOM
- [ ] **CLI**
  - [ ] Markdown Transform
- [ ] **Specs**
  - [ ] CiceroMark

## Related Issues:
- https://github.com/accordproject/cicero/issues/547

**Comment by jeromesimeon** [comment]
@irmerk I think covered with #306 ?
