### ISSUE TITLE
Website Documentation doesn't align to the current command line executable help

### ISSUE THREAD

**Issue by JohnGr001** [accordproject/techdocs#303]
[**Describe](url
[Document Ticket.zip]
(https://github.com/accordproject/techdocs/files/5043546/Document.Ticket.zip)

) the bug**
The attached zip file contains a html5 map. The items noted in **red** are out of date. The markus online help needs rework, the other changes are more cosmetic. 

**To Reproduce**
Click on the links or follow the help in the web pages. Then use the latest command line tool and compare the help output. 
Ig you cannot open the zip file or HTML5 map , let me know, 

**Expected behavior**
The documents should match the current release (where possible) 

**Screenshots**
See zip file and extract the HTML5 map

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome , but will be the same for all browsers. 

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jeromesimeon** [comment]
Some initial update to the Markus CLI documentation, aligning with the current version, is in #306

**Comment by irmerk** [comment]
This will be tracked and solved in #306

**Comment by jeromesimeon** [comment]
New Markdown Transform CLI published as `0.21` documentation.
