### ISSUE TITLE
[Question] How to deploy to Fabric: ERROR: manifest for hyperledger/fabric-ca:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by scheung38** [accordproject/techdocs#305]
Following in here:

https://accord.gitbook.io/accord-project/#on-amazon-web-services

Provision your Hyperledger Fabric instance

git clone https://github.com/clauseHQ/fabric-samples
cd fabric-samples
git checkout master

cd fabric-samples/cicero

./startFabric.sh 

export MSYS_NO_PATHCONV=1

docker-compose -f docker-compose.yml down
Removing network net_basic

docker-compose -f docker-compose.yml up -d ca.example.com orderer.example.com peer0.org1.example.com couchdb
Creating network "net_basic" with the default driver
Pulling ca.example.com (hyperledger/fabric-ca:)...
ERROR: manifest for hyperledger/fabric-ca:latest not found: manifest unknown: manifest unknown

How do we install ?

**Comment by jeromesimeon** [comment]
@mttrbrts are those amazon images those you had built for a demo / tutorial a while back? Are they related to the HLF tutorial in the documentation? CC @dselman

**Comment by X00159370** [comment]
I have a loader/tutorial I can add. One covers v1.4.6 of hlf , the other is written for hlf v2 (suitable for the hlf project) and builds on the new test network. Happy to contribute

**Comment by dselman** [comment]
Please follow the new guide, here: https://deploy-preview-309--accordproject-docs.netlify.app/docs/next/tutorial-hyperledger.html
