### ISSUE TITLE
ergo commands installed

### ISSUE THREAD

**Issue by adriaan-pelzer** [accordproject/techdocs#31]
**Ergo** installation section of the [documentation](https://docs.accordproject.org/docs/accordproject-tools.html) refers to 2 installed ergo commands: **ergoc** and **ergo**.
According to the docs, ergo needs to be tested as such:
ergo execute --help
There is no such command installed, however. The installed commands seem to be:
**ergoc**
**ergorun**
**ergotop**

**Comment by mttrbrts** [comment]
Thanks for raising an issue @adriaan-pelzer, it seems that we haven't released the latest version of the documentation yet. The `next` build includes the changes (https://docs.accordproject.org/docs/next/accordproject-tools.html). I'll get a release out shortly.

Sorry for any inconvenience.

**Comment by adriaan-pelzer** [comment]
No worries - thanks for your quick reply!

**Comment by adriaan-pelzer** [comment]
Shouldn't that be
```ergorun execute --help```

**Comment by mttrbrts** [comment]
@jeromesimeon can you review the docs again, please? It seems like there are a few issues remaining

**Comment by jeromesimeon** [comment]
Thanks @mttrbrts and @adriaan-pelzer. I thought it was done, let me look at it again.

@adriaan-pelzer 

It should just be `ergorun [options] files` and `ergoc [options] files`, no need for `execute`.

**Comment by jeromesimeon** [comment]
Should be fixed in the latest version of the documentation, which is now online: https://docs.accordproject.org
