### ISSUE TITLE
Documentation Video link is broken

### ISSUE THREAD

**Issue by sofiter** [accordproject/techdocs#327]
**Describe the bug**
Some links are broken

**To Reproduce**
1. Go to https://docs.accordproject.org/docs/accordproject-tour.html
2. Click on the video
3. There is aproblem displaying the video from vimeo on this page

**Expected behavior**
The video should have a valid link

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 87.0.4280.66

**Comment by jeromesimeon** [comment]
@sofiter I think the video should work again, could you confirm?

**Comment by sofiter** [comment]
Yes, all good now, should I close the issue?

**Comment by jeromesimeon** [comment]
> Yes, all good now, should I close the issue?

yes please!
