### ISSUE TITLE
Documentation link returns a page not found error

### ISSUE THREAD

**Issue by sofiter** [accordproject/techdocs#328]
**Describe the bug**
Some links are broken

**To Reproduce**
1. Go to https://docs.accordproject.org/docs/model-decorators.html
2. Click on the Decorators Reference hyperlink
3. A page not found is returned

**Expected behavior**
The link should redrect to the according page

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 87.0.4280.66

**Comment by Aniruddha-Shriwant** [comment]
@irmerk , similar to #329 the "Decorators Reference hyperlink" is broken, I think it should point to [this](https://docs.accordproject.org/docs/ref-concerto-decorators.html)

**Comment by Aniruddha-Shriwant** [comment]
> @irmerk , similar to #329 the "Decorators Reference hyperlink" is broken, I think it should point to [this](https://docs.accordproject.org/docs/ref-concerto-decorators.html)

@irmerk May I add this change in #343 ?

**Comment by irmerk** [comment]
@Aniruddha-Shriwant sure just add them both to the same PR that's open.

**Comment by Aniruddha-Shriwant** [comment]
Okay :)

**Comment by Aniruddha-Shriwant** [comment]
This is resolved by #337
