### ISSUE TITLE
Documentation: Broken link

### ISSUE THREAD

**Issue by Aniruddha-Shriwant** [accordproject/techdocs#344]
# Bug Report 🐛

Hyperlink in documentation is broken

Similar Issues : #328 & #329 

## Expected Behavior
Should point to a specific page. 

## Current Behavior
After clicking the hyperlink it gives a page not found error.

## Possible Solution
Changing link in `.md file`

## Steps to Reproduce

1. Go to [TemplateMark](https://docs.accordproject.org/docs/accordproject-template.html#templatemark) section in Accord Project Templates
2. Click on the  **Markdown Text** hyperlink
3. A page not found is returned

### Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.190

**Comment by Aniruddha-Shriwant** [comment]
@irmerk should I add commit for this in #343 ?

**Comment by irmerk** [comment]
Yeah that sounds good @Aniruddha-Shriwant

**Comment by Aniruddha-Shriwant** [comment]
Ohk I will add that commit... :)
