### ISSUE TITLE
Link to Cicero documentation is broken in the Accord Project Technical Integration note below each template

### ISSUE THREAD

**Issue by dinuka-rp** [accordproject/techdocs#349]
# Bug Report 🐛
Broken Redirect link to Cicero documentation from Templates under the Template Library.

## Expected Behavior
Redirect the user to Cicero documentation

## Current Behavior
The user is redirected to https://docs.accordproject.org/docs/cicero.html

The following screen is shown.
![Screenshot_20210313_021500](https://user-images.githubusercontent.com/47103883/110996426-ed59f100-83a1-11eb-8f90-d713815645aa.png)

## Possible Solution
As I understand, the link should redirect the user to https://docs.accordproject.org/docs/started-installation.html

## Steps to Reproduce
1. Open https://templates.accordproject.org/full-payment-upon-signature@0.10.0.html
2. Scroll to the bottom of the page, to the **Techincal Integration** section
3. Click on ``` Cicero documentation```

## Context (Environment)
I was reading through the project website and documentation in order to understand the project and came across this issue. Thought that someone else might run into the same issue as well.

### Desktop
 - OS: Kubuntu 20.04
 - Browser: Chrome
 - Version: 89.0.4389.82 (Official Build) (64-bit)

**Comment by dinuka-rp** [comment]
If the proposed solution is correct, I would like to get assigned to this issue and fix it.

**Comment by mttrbrts** [comment]
Thanks @dinuka-rp, you have the correct URL but this change isn't straightforward.

The site https://templates.accordproject.org is actually statically built by in the `cicero-template-library` (e.g. https://github.com/accordproject/cicero-template-library/blob/master/build/full-payment-upon-signature%400.10.0.html)

So we have two options:
1. Update all of the pages in the `build` folder in the `cicero-template-library` folder.
2. Add a redirect proxy in the documentation site so that the link will work again. This may not be possible with Docusaurus.

**Comment by dinuka-rp** [comment]
@mttrbrts, I wondered around the code-base and found out that there's a much easier way of changing this.
This can be fixed by changing [this](https://github.com/accordproject/cicero-template-library/blob/master/views/developers.njk#L84) line of code and running the build command.

All pages in the build file will be updated then 😄

Shall I open this issue in the ```cicero-template-library``` project and send a PR to that repo?

Thanks for pointing out that that documentation was in a separate repository.

**Comment by mttrbrts** [comment]
Unfortunately, I worry that it's not quite that easy. The files were all built by historical versions of the Cicero engine and rebuilding is likely to break other parts of the page if we rebuild with a more recent Cicero version. I'd love to be proven wrong!

Alternatively, you could just do a find/replace to be sure that we're only changing that line?

You're right about moving this issue though. Please close this issue and open a new one in `cicero-template-library`.

**Comment by dinuka-rp** [comment]
Oh, I see...
I'll try doing a find/ replace for now since you're not sure if it'll break and I'm also kinda new here. Don't want to be breaking the docs or the templates 😅.

I'm guessing that when the PR is merged, the built files will get deployed without trying to rebuild the entire project?
Is it ok to update [this](https://github.com/accordproject/cicero-template-library/blob/master/views/developers.njk#L84) line as well?

Will close the issue here and reopen it in the `cicero-template-library` repo for now.
