### ISSUE TITLE
Publishing JS Guidelines in the TechDocs

### ISSUE THREAD

**Issue by Cronus1007** [accordproject/techdocs#355]
# Discussion 🗣
Lack of Javascript Coding Guidelines
- reduces efficiency of communication and pull requests
- sets new contributors up to fail
- increases cognitive work of working across multiple repositories

# Solution Description
Document Javascript coding guidelines.

- [x]  Communicate with stakeholders
- [x]  Draft guidelines
- [x]  Publish guidelines

## Context
For example:

- nodev14
- eslint
- stylelint

**Comment by irmerk** [comment]
I think this can be folded into #308
