### ISSUE TITLE
adding .editorconfig and browserlist

### ISSUE THREAD

**Issue by Cronus1007** [accordproject/techdocs#356]
# Discussion 🗣

- Add the .editorconfig
- Add the .browserslistrc

## Context
- EditorConfig is a universal solution which should tremendously reduce the amount of arguing between the developers. Moreover, in order to setup a basic `.editorconfig` should take no longer than 3–4 minutes.
- Browserslist is a convenient tool for describing target browsers just by using simple queries. For more info have look 
https://dev.to/dangreen/speed-up-with-browserslist-30lh

**Comment by irmerk** [comment]
I think this can be folded into #308
