### ISSUE TITLE
About project

### ISSUE THREAD

**Issue by haroonahmed-sudo** [accordproject/techdocs#380]
Hey, I'm a beginner. I don't know anything about open source projects but I'm really skillful in frontend and backend so what I need to do in this project. please someone guide me.

**Comment by irmerk** [comment]
I would google "`how contribute open source site:dev.to`" for reference material, or use the [opensource.guide](https://opensource.guide/how-to-contribute/). As for Accord Project, start with [getting familiar with the tech](https://docs.accordproject.org/docs/started-installation.html) and then browsing the open issues [in repositories](https://github.com/accordproject).
