### ISSUE TITLE
underlining of titles of features

### ISSUE THREAD

**Issue by shubhangi013** [accordproject/techdocs#381]
# Bug Report 🐛
The titles of the features blocks like : 'Concerto' are underlined upon hovering.

## Expected Behavior
Since two of the titles: 'CICERO' and 'ERGO' are actually images, there is no underlining upon hovering. The same should happen with 'Concerto' and the other 2.

## Current Behavior
The other 2 along with 'Concerto' get underlined.

## Steps to Reproduce

1.Open the link : https://docs.accordproject.org/
2. hover over the features' titles.

### Desktop
 - OS: [e.g. macOS]  Ubuntu 20.04.2 LTS
 - Browser: [e.g. Chrome, Safari] Firefox 
 - Version: [e.g. 0.22.15] 91.0.2 (64-bit)

## Detailed Description

The anchor tags already have 'text-decoration: none' but it isn't working. I can fix this.

**Comment by salmanansari14** [comment]
I want to contribute

**Comment by shubhangi013** [comment]
> I want to contribute
> 

I've already opened a PR that resolves this issue.

**Comment by gauravgupta9755** [comment]
i will want to contribute

**Comment by irmerk** [comment]
@Michael-Grover do you have thoughts on this and the related PR #382?

**Comment by Michael-Grover** [comment]
thanks for tagging me @irmerk , I added comments on the PR. I think it looks good from the Netlify preview, but I think it would be good for a front-end engineer to look before merging, to confirm that only the intended links are affected.
