### ISSUE TITLE
Removing signup button

### ISSUE THREAD

**Issue by shivesh01** [accordproject/techdocs#383]
# Bug Report 🐛
Join button is not working

## Expected Behavior
open a content page

## Current Behavior
"Ooops, this page does not exist"

## Possible Solution
- Add a link to it.
- Or remove the button.

## Steps to Reproduce
First link gives the location where button exits and second link output of the button.
[button page](https://accordproject.org/about/)
[button output page](https://accordproject.org/signup)

## Context (Environment)
Reading through the documentation I found out this page.
### Desktop
 - OS: [macOS]
 - Browser: [ Chrome]
 - Version: [93.0.4577.82]

## Detailed Description
Join the Accord Project button is not working in about section.

## Possible Implementation
If we want button to be remain, then we should add a link to it. Otherwise, it should be removed

**Comment by shivesh01** [comment]
I think it's good idea to add discord channel link to it instead of removing the button.

**Comment by Michael-Grover** [comment]
I've changed the link to direct users to the discord signup page. @shivesh01 thanks for reporting the bug.
