### ISSUE TITLE
Spelling error in templateGuides/preliminaries.

### ISSUE THREAD

**Issue by amanag25** [accordproject/techdocs#391]
# Bug Report 🐛

There is spelling error in TemplateGuides/preliminaries. BlockName is misspelled as BlockBane.
![issue1](https://user-images.githubusercontent.com/92196600/144732963-42238ce3-e26b-4331-a107-e3c406434baf.png)

**Comment by prathamaror** [comment]
i would like to work on this issue

**Comment by amanag25** [comment]
> i would like to work on this issue

I've already attached a PR that resolves this issue
