### ISSUE TITLE
Documentation: Specs link under Coding Rules in Developers.md not working

### ISSUE THREAD

**Issue by Jeevan-Kiran-Lenka** [accordproject/techdocs#403]
# Discussion 🗣 

**Documentation: Specs link under Coding Rules in Developers.md not working**
## Context

When working on the source code yo ensure consistency throughout, all features or bug fixes must be tested by one or more [specs](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#unit-tests).

here the `specs` link is pointing to the same file so from where we can see those specifications?, and if there's a correct link for this

**Comment by Jeevan-Kiran-Lenka** [comment]
Hey!! @arpit-maurya, I'm not the maintainer for this project, Please ask @mttrbrts, @dselman, @irmerk for assigning this to you :)

**Comment by irmerk** [comment]
Open a PR if you want to work on this.
