### ISSUE TITLE
Missing Commit Message Conventions

### ISSUE THREAD

**Issue by anablaz** [accordproject/techdocs#423]
# Bug Report 🐛

When submitting my first pull request, I noticed that I've been prompted several times to adhere to the "commit message conventions". The documentation of the convention is supposed to be on a documentation page, but it seems to be missing.

## Expected Behavior

There should be a section on commit message conventions on this page: https://github.com/accordproject/techdocs/blob/main/DEVELOPERS.md#commits

## Current Behavior

The information about commit message conventions is missing.

## Possible Solution

I'd like to (re)add it, could you please let me know what would you like in it?

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Upon checking out some other Accord repositories, I noticed they all tend to lead to this page in the techdocs repository as well, so it's something that impacts the whole organisation.

### Desktop
 - OS: [e.g. macOS]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 0.22.15]

**Comment by sanketshevkar** [comment]
Hi @anablaz 
Can you please confirm if you are looking for [this](https://github.com/accordproject/techdocs/blob/main/CONTRIBUTING.md#-issue-submission-guidelines)?

**Comment by anablaz** [comment]
Hello,

@sanketshevkar, the missing information that I'm talking about is also referenced on the page you linked - in the Pull Request Submission Guidelines section of the page, there are two hyperlinks titled "commit message conventions". Upon clicking either of them, the link takes you to the [site](https://github.com/accordproject/techdocs/blob/main/DEVELOPERS.md#commits) I listed when opening this issue.

This issue is about the fact that there is no commit message conventions information on the [link](https://github.com/accordproject/techdocs/blob/main/DEVELOPERS.md#commits). I'm assuming it used to be documented there, since it's referenced both in [the pull request submission guidelines](https://github.com/accordproject/techdocs/blob/main/CONTRIBUTING.md#-issue-submission-guidelines) as well as on the [developer checklist](https://github.com/accordproject/techdocs/blob/main/.github/pull_request_template.md) when you make a pull request  (the check for "commits messages follow AP format").

**Comment by sanketshevkar** [comment]
Thanks for the detailed explanation @anablaz.
Yes you are right we need commit convention rules linked. This what we follow https://www.conventionalcommits.org/en/v1.0.0/

@DianaLease I remember having details about conventional commits, but they are not present there now.
