### ISSUE TITLE
Link point to the same document 

### ISSUE THREAD

**Issue by wasup-yash** [accordproject/techdocs#424]
# Bug Report 🐛

[here](https://github.com/accordproject/techdocs/blob/main/DEVELOPERS.md#commits) the link in the document point to the same document 

## Expected Behavior

The link should not be there I suppose?

## Current Behavior

the link is there and points to the same document.

## Possible Solution

removing the link ? 

### Desktop
 - OS: [Debian 12 ]
 - Browser: [Chrome]
 - Version: [e.g. 0.22.15]

**Comment by wasup-yash** [comment]
I want to work on this issue if this is a valid issue?

**Comment by Shahbaz898414** [comment]
I want to work on this issue if this is a valid issue?

**Comment by anablaz** [comment]
Hi, you can just send in a pull request with your fix and see what the feedback will be.

On a semi-related note, here is another issue you might want to close as well with your pull request: https://github.com/accordproject/techdocs/issues/403

As you can see in this issue, there used to be a "specs" link in the DEVELOPMENT.md file. As you can see from the "specs" link name: https://github.com/accordproject/techdocs/blob/main/DEVELOPERS.md#unit-tests, there used to be a section in this file on unit tests. Perhaps you can gather information on that (for example on Discord) and add it in your pull request.
