### ISSUE TITLE
Brand assets URLs are broken

### ISSUE THREAD

**Issue by timothytavarez** [accordproject/techdocs#436]
# Bug Report 🐛
Brand Assets URLs [https://accordproject.org/brand-assets](https://accordproject.org/brand-assets) are currently broken. The following three HREF resolve to Google Drive / Google Slides assets which are no longer accessible:

- [Download Brand assets](https://drive.google.com/a/clause.io/file/d/11fcFHhSa6jz0WuUW6KK6cy3A4d_4lFNF/view?usp=sharing)
- [Download Style Guide](https://drive.google.com/open?id=1DSBo1g3ABq58FyxasHIokokyXXHg7vXj)
- [Download Accord Project presentation template](https://docs.google.com/presentation/d/1lWhgR-TOeRV_MQRTraSVHLRqqge-W9g9sgwRnCruXo8/edit?usp=sharing)

![image](https://github.com/accordproject/techdocs/assets/16512835/2a6b801b-7f9c-42a0-b520-1729ea548452)

## Expected Behavior
Links should resolve to assets.

## Current Behavior
All links are broken and resolve to 404 / errors.

## Possible Solution
Locate previous assets and upload to centralized repository (e.g., GitHub?)

## Steps to Reproduce
1. Visit https://accordproject.org/brand-assets.
2. Attempt to access any of the content URLs for assets.

### Desktop
 - Confirmed on Microsoft Edge for Business Browser Version 122.0.2365.92 (Official build) (64-bit)

**Comment by mttrbrts** [comment]
Fixed!
