### ISSUE TITLE
Incorrect namespace defined across documentation.

### ISSUE THREAD

**Issue by adrianffletcher** [accordproject/techdocs#65]
The namespace for importing accord project files is specified as 'ord.accordproject' in many places rather than 'org.accordproject'

One example is here:
https://docs.accordproject.org/docs/ergo-stdlib.html

<img width="888" alt="Screenshot 2019-07-11 at 14 29 43" src="https://user-images.githubusercontent.com/29235349/61055188-d99a0280-a3e8-11e9-837d-e2a78f4f0bd2.png">

**Comment by carolinaknoll** [comment]
Hello, can I take this one for Hacktoberfest for a pair programming session?

Also, thank you for creating very detailed issues and a highly descriptive contributing guide. 🎉 ✨

**Comment by oorjitchowdhary** [comment]
hi can i take this up?
i'll be sending a PR in a while

**Comment by oorjitchowdhary** [comment]
@carolinaknoll oh! i couldn't see activity on this issue the past week so i thought of making a PR.
i already completed it though. let @adrianffletcher merge your PR and just leave mine as is.

**Comment by irmerk** [comment]
@carolinaknoll very sorry I didn't see your post! Feel free to put in a PR for this issue, or take on another one. Let me know which you'd prefer, and I'll assign you to the issue.

**Comment by mttrbrts** [comment]
Fixed by @oorjitchowdhary in #97
