### ISSUE TITLE
Dynamic Template Documentation

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#68]
Accord Project documentation needs to be updated to represent new information on our control of the contract text by embedding logic in the templates. This involves:
  - Constructing Tables & Lists
  - Handling Text Dependencies
  - Handling Optional Text (with Parameters)
  - Handling Complex Data

This will also cover syntax updates, which can be viewed more in [Cicero Issue #392][syntaxIssue]
  
  This will encompass [ergo][ergo], [cicero][cicero], [cicero-template-library][cicero-template-library], [models][models], [cicero-ui][cicero-ui], and [template-studio-v2][template-studio-v2]

[syntaxIssue]: https://github.com/accordproject/cicero/issues/392  
[ergo]: https://github.com/accordproject/ergo
[cicero]: https://github.com/accordproject/cicero
[cicero-template-library]: https://github.com/accordproject/cicero-template-library
[models]: https://github.com/accordproject/models
[cicero-ui]: https://github.com/accordproject/cicero-ui
[template-studio-v2]: https://github.com/accordproject/template-studio-v2

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by jeromesimeon** [comment]
The 0.20 documentation includes a new Guide on rich text, complex data, and dynamic templates with Ergo expressions.
