### ISSUE TITLE
TSv2 Documentation

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#71]
Accord Project documentation needs to be updated to represent our new template studio and its features. This involves:
  
This will encompass [cicero-ui][cicero-ui] and [template-studio-v2][template-studio-v2]

[cicero-ui]: https://github.com/accordproject/cicero-ui
[template-studio-v2]: https://github.com/accordproject/template-studio-v2

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by VishalS99** [comment]
I guess I can take this up! Could you brief me as to what all has to be updated? Thanks!

**Comment by avi-007** [comment]
I want to work on this issue

**Comment by irmerk** [comment]
Opening this back up after 8 days stale.
