### ISSUE TITLE
Documentation Versioning

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#75]
Indicate "Documentation" for all instances of versioning.

- Header between logo and version
- `Current Documentation Version (Stable)`
- `Pre-Release Documentation Versions`
- `Past Documentation Versions`

<img width="727" alt="Screen Shot 2019-08-21 at 1 47 21 PM" src="https://user-images.githubusercontent.com/36460856/63455198-4ce85880-c41a-11e9-96ea-4e24f1bbc9f8.png">

**Comment by jeromesimeon** [comment]
@irmerk I'm not sure I understand the ask here. What would you like to see changed?

**Comment by irmerk** [comment]
In the screenshot, these:
```
Current version (Stable)
Pre-release versions
Past Versions
```
would be changed to these:
```
Current Documentation Version (Stable)
Pre-Release Documentation Versions
Past Documentation Versions
```

**Comment by jeromesimeon** [comment]
> In the screenshot, these:
> 
> ```
> Current version (Stable)
> Pre-release versions
> Past Versions
> ```
> 
> would be changed to these:
> 
> ```
> Current Documentation Version (Stable)
> Pre-Release Documentation Versions
> Past Documentation Versions
> ```

I like the idea to change `version` to `Version` so it looks uniform, but is adding `Documentation` really an improvement? Since everything in that Web site is documentation, isn't it redundant?

Maybe changing the title of that page to be clearer than "Accord Project Versions" would be nice.
