### ISSUE TITLE
Downloads Badges

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#77]
**Is your feature request related to a problem? Please describe.**
We should display a badge for downloads on repositories' main `README` which are downloaded, including:
- `ergo`
- `cicero`
- `cicero-ui`
- `markdown-editor`
- `markdown-transform`
- `slate-markdown-transform`
- etc...

**Describe the solution you'd like**
Reference [`styled-components`](https://github.com/styled-components/styled-components):
![Screen Shot 2019-09-10 at 14 21 23 PM](https://user-images.githubusercontent.com/36460856/64639677-512ee280-d3d6-11e9-8e93-22d870feabb0.png)

**Describe alternatives you've considered**
Open to alternatives.

**Additional context**
- May need accumulating data, for example `cicero` consists of `cicero-cli`, `cicero-core`, etc.
- [Starting point for badges here](https://shields.io/)

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by RanadeepPolavarapu** [comment]
I'll take care of this.

**Comment by RanadeepPolavarapu** [comment]
All 5 PRs linking to this issue are signed off with a DCO.

**Comment by irmerk** [comment]
We'll want this for `cicero-ui` as well.

**Comment by irmerk** [comment]
@jeromesimeon I think this is still needed in `cicero-ui`, no?

**Comment by jeromesimeon** [comment]
I'm not sure how I ended up closing this. Apologies!

**Comment by RanadeepPolavarapu** [comment]
My apologies, I forgot to open that PR.

accordproject/cicero-ui#149

**Comment by irmerk** [comment]
Yeah @jeromesimeon there is some weird behavior with GitHub it looks like.
