### ISSUE TITLE
Slack Badges

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#78]
**Is your feature request related to a problem? Please describe.**
We should display a badge for our slack on repositories' main `README`, including:
- `ergo`
- `cicero`
- `cicero-ui`
- `markdown-editor`
- `markdown-transform`
- `slate-markdown-transform`
- `template-studio-v2`
- `cicero-vscode-extension`
- `cicero-template-library`
- `models`
- ~`techdocs`~ (**FINISHED** @4katie)
- etc...

**Describe the solution you'd like**
Reference [`babel`](https://github.com/babel/babel):
![Screen Shot 2019-09-10 at 14 28 53 PM](https://user-images.githubusercontent.com/36460856/64640162-6a845e80-d3d7-11e9-9ac5-1abbbab01d54.png)

**Describe alternatives you've considered**
Open to alternatives.

**Additional context**
[Starting point for badges here](https://shields.io/)

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by aayushbisen** [comment]
I like to work on this one. 👋

**Comment by aayushbisen** [comment]
I have 2 more PR's ready for #82 and this.
Since both issues are closed now.
Can I still submit the PR's?

**Comment by irmerk** [comment]
Yes @aayushbisen, I believe we still need this for the majority of our repositories.

**Comment by irmerk** [comment]
@aayushbisen I believe the Lerna links are wrong - should be `https://lerna.js.org/`

**Comment by aayushbisen** [comment]
> @aayushbisen I believe the Lerna links are wrong - should be `https://lerna.js.org/`

Ok I'll update that.

**Comment by irmerk** [comment]
Repos that need updating to say "Accord Project - Join Slack" such as in [`markdown-editor`](https://github.com/accordproject/markdown-editor):

- [ ] [`cicero`](https://github.com/accordproject/cicero)
- [ ] [`ergo`](https://github.com/accordproject/ergo)
- [ ] [`concerto`](https://github.com/accordproject/concerto)
- [ ] [`models`](https://github.com/accordproject/models)
- [ ] [`cicero-template-library`](https://github.com/accordproject/cicero-template-library)
- [ ] [`template-studio-v2`](https://github.com/accordproject/template-studio-v2)
- [ ] [`cicero-vscode-extension`](https://github.com/accordproject/cicero-vscode-extension)

**Comment by aayushbisen** [comment]
On it!

**Comment by aayushbisen** [comment]
All done I think. ✅
