### ISSUE TITLE
Ecosystem Description Table

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#80]
**Is your feature request related to a problem? Please describe.**
We should display a table for our ecosystem on repositories main `README`, including:
- `ergo`
- `cicero`
- `cicero-ui`
- `markdown-editor`
- `markdown-transform`
- `slate-markdown-transform`
- `template-studio-v2`
- `cicero-vscode-extension`
- `cicero-template-library`
- `models`
- etc...

**Describe the solution you'd like**
Reference [`vue`](https://github.com/vuejs/vue):
![Screen Shot 2019-09-10 at 14 40 51 PM](https://user-images.githubusercontent.com/36460856/64640913-08c4f400-d3d9-11e9-9beb-3e9511f23d33.png)

Our table should consist of:
- Core:
  - `ergo`
  - `cicero`
- Cicero
  - `cicero-template-library`
  - `models`
- Markdown
  - `markdown-editor`
  - `markdown-transform`
  - `slate-markdown-transform`
- User Interface
  - `cicero-ui`
  - `template-studio-v2`
- Developer Tools
  - `cicero-vscode-extension`

**Describe alternatives you've considered**
Open to alternatives. Get feedback from @jeromesimeon @dselman and @mttrbrts 

**Additional context**
[Starting point for badges here](https://shields.io/)

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by daniloff200** [comment]
I can took this one too, but, I have one question: Is it okay If I make table with the same structure, like in vue example, or, we really need a sub heading for each section, like :

Core 
Project                Status             Description
ergo                    badge              some descr
cicero                  badge              some descr

User Interface
Project                Status             Description
cicero-ui                    badge              some descr
template-studio-v2                  badge              some descr

**Comment by irmerk** [comment]
@daniloff200: I'm pretty sure I understand! I think the option you proposed sounds better, having sub-headings. There are some pretty distinct borders, so that sounds like the right path.

**Comment by irmerk** [comment]
@jeromesimeon https://github.com/accordproject/techdocs/pull/131#issuecomment-540212205

In reference to this, I don't think we expect our ecosystem to change so often that this would be hard to maintain - I think it would take little to no maintenance.

**Comment by jeromesimeon** [comment]
> @jeromesimeon [#131 (comment)](https://github.com/accordproject/techdocs/pull/131#issuecomment-540212205)
> 
> In reference to this, I don't think we expect our ecosystem to change so often that this would be hard to maintain - I think it would take little to no maintenance.

We re-publish those things quite often. I just want to make sure we do not add too much extra work for this.

When things change, if those aren't maintained this will confused users more rather than less.

(I think this was the same idea when we added `DEVELOPER.md` etc to every project, and obviously we have tons of inconsistencies across those and have to fix typos in all the different places).

**Comment by daniloff200** [comment]
I agree with @irmerk, I don't think that new modules / libraries will appear every release. 
If you're confused because of version badge, that should be updated automatically, I suppose

**Comment by irmerk** [comment]
> We re-publish those things quite often. I just want to make sure we do not add too much extra work for this.

Does this change the way the ecosystem is shaped? If auto generating this from one source is possible, then we can just do that.

I think later in October or post Hacktoberfest, having one task be to sync all `DEVELOPERS` files again isn't too onerous.

**Comment by irmerk** [comment]
Based on the latest response (https://github.com/accordproject/techdocs/pull/131#issuecomment-541226731), I was thinking of this to look more like this (https://github.com/accordproject/techdocs/pull/131#issuecomment-538763708) and this (https://github.com/accordproject/techdocs/pull/131#issuecomment-539713452).

Where does this stand @jeromesimeon?

**Comment by daniloff200** [comment]
@irmerk  I got your point, I personally more like these two options, then how I made it now, but, it was per https://github.com/accordproject/techdocs/pull/131#issuecomment-540084748 this . Let's wait for feedback from Jerome !

**Comment by irmerk** [comment]
This issue will be the tracker for all PRs in other repos. Make sure to link to this when creating more PRs @daniloff200

**Comment by irmerk** [comment]
Adding a checklist @daniloff200:

- [x] `ergo` (@daniloff200)
- [x] `cicero` (@daniloff200)
- [ ] `concerto` (@daniloff200)
- [ ] `markdown-transform`
- [ ] `markdown-editor`
- [ ] `cicero-ui`
- [ ] `concerto-ui`
- [ ] `template-studio-v2`
- [ ] `cicero-vscode-extension` (@daniloff200)
- [ ] `cicero-template-library`
- [ ] `models`
- [ ] `techdocs`

**Comment by daniloff200** [comment]
techdocs actually already fixed and merged, we're in this repo now, ahahah :rofl:  @irmerk

**Comment by daniloff200** [comment]
@irmerk  looks like I've created a PRs for all items from your checklist :) waiting for reviews!

**Comment by irmerk** [comment]
Nice, thank you for all the consistency and thoroughness!

**Comment by jeromesimeon** [comment]
There are already discrepencies between some of those tables in different projects. e.g., between Concerto: https://github.com/accordproject/concerto/blob/master/README.md and Cicero: https://github.com/accordproject/cicero/blob/master/README.md

**Comment by daniloff200** [comment]
@jeromesimeon  ohhhh my god!
That was a missclick ! And that was only in one repo: in Cicero. 
I missed `concerto-ui` there. Gonna create a fix right now.

In all other repos, tables are exactly the same
 

`

**Comment by daniloff200** [comment]
Well, I see, that I failed a little bit, and link to markdown editor package is broken in every repo :mask: 

Gonna create PRs today in all repos with a fix

**Comment by irmerk** [comment]
@daniloff200 link them all to this issue and we can review them all at once again.

**Comment by daniloff200** [comment]
Well, looks like that's all 
cc @irmerk  @jeromesimeon
