### ISSUE TITLE
Accord Project Badge

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#81]
**Is your feature request related to a problem? Please describe.**
We should create a custom Accord Project badge, available in our published repositories' main `README`, including:
- `ergo`
- `cicero`
- `cicero-ui`
- `markdown-editor`
- `markdown-transform`
- `slate-markdown-transform`
- etc...

**Describe the solution you'd like**
Reference [`styled-components`](https://github.com/styled-components/styled-components):
![Screen Shot 2019-09-10 at 14 48 54 PM](https://user-images.githubusercontent.com/36460856/64641426-28105100-d3da-11e9-96cd-31d18ae4da16.png)

**Describe alternatives you've considered**
Open to alternatives. Get input from @Michael-Grover on design.

**Additional context**
[Starting point for badges here](https://shields.io/)

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by michizhou** [comment]
I can definitely tackle this issue! Feel free to assign it to me.

**Comment by irmerk** [comment]
Great @michizhou! A good starting point could be the work @4katie did in #89.

**Comment by irmerk** [comment]
Opening back up after 20 days stale.

**Comment by michizhou** [comment]
@irmerk I deeply apologize for not updating you on my progress for this issue. I have been working on this, and should be able to get the documentation ready for review by later today. If you could reassign this issue to me, I would greatly appreciate it. Thank you.

**Comment by irmerk** [comment]
I believe #192 may be the wrong approach. This may need a step back and evaluate how we can create a badge that is synced up with the latest version of `cicero`/`ergo` that other developers could use. Or a badge to place on their website, even.

**Comment by michizhou** [comment]
@irmerk Should we put #192 on hold until further notice then?

**Comment by irmerk** [comment]
I think putting it on hold until after our working group call tomorrow - I'll bring this up as a point of discussion. Feel free to join, 4pm EST https://zoom.us/j/5230278722

**Comment by irmerk** [comment]
Based on the discussion, I think we want to implement a badge like the one you created, but remove the reference to a version. That way, this can refer to using `cicero-ui`, or any other library that might not be synced up in versions. We'll want this to be accessible to developers to use in their codebase, so maybe having a small section in the `techdocs` README file regarding this.

We also want to implement a section within the docs where we showcase a logo for "Powered by Accord Project", which I uploaded [here](https://github.com/accordproject/techdocs/blob/master/assets/POWEREDBY-MARK-AND-TEXT.svg). This will be for use in someones website to indicate the technology they are running.

**Comment by jeromesimeon** [comment]
@michizhou Any progress on this?

**Comment by michizhou** [comment]
@jeromesimeon I've decided to hold off on working this issue for the moment (which is further evidenced by the fact that the PR I used for this issue has been closed for a few days now).

@irmerk Should we resume work on this? If so, feel free to reopen the old PR or let me know if you want us to progress further so I can open a new PR to continue working on this issue.

**Comment by jeromesimeon** [comment]
oh I had missed that closed PR. thanks for the update @michizhou !

**Comment by irmerk** [comment]
Work could resume on this based on the info in this comment https://github.com/accordproject/techdocs/issues/81#issuecomment-548122651

I suspect the previous PR wouldn't necessarily be the right direction, so maybe starting fresh?

**Comment by jeromesimeon** [comment]
How about something as simple as this? [![accord project](https://img.shields.io/badge/powered%20by-accord%20project-19C6C8.svg)](https://www.accordproject.org/)

````
### README Badge

Using Accord Project? Add a README badge to show it off: [![accord project](https://img.shields.io/badge/powered%20by-accord%20project-19C6C8.svg)](https://www.accordproject.org/)

```
[![accord project](https://img.shields.io/badge/powered%20by-accord%20project-19C6C8.svg)](https://www.accordproject.org/)
```
````

**Comment by irmerk** [comment]
Finished in `cicero`, #535 needs to be done in the following:

- [ ] `ergo`
- [x] `cicero`
- [ ] `concerto`
- [ ] `markdown-transform`
- [ ] `markdown-editor`
- [ ] `models`
- [ ] `cicero-template-library`
- [ ] `techdocs`
- [ ] `concerto-ui`
- [ ] `cicero-ui`
- [ ] `cicero-vscode-extension`

**Comment by jeromesimeon** [comment]
I think that in `cicero-template-library` it should be actually at the top of the README as if it was user code -- as well as with instructions on how to use the badge.

**Comment by jeromesimeon** [comment]
In Cicero Template Library:

<img width="579" alt="Screenshot 2020-04-06 at 5 34 57 PM" src="https://user-images.githubusercontent.com/670099/78607382-f3a82a80-782c-11ea-9ea3-816f20a03753.png">

In the models repository:

<img width="579" alt="Screenshot 2020-04-06 at 5 34 57 PM" src="https://user-images.githubusercontent.com/670099/78607446-0fabcc00-782d-11ea-9018-bc3fbf0fa43e.png">
