### ISSUE TITLE
Contributors Section in README

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#83]
**Is your feature request related to a problem? Please describe.**
We should add a contributors section in our repositories' main `README`, including:
- `ergo`
- `cicero`
- `cicero-ui`
- `markdown-editor`
- `markdown-transform`
- `slate-markdown-transform`
- `template-studio-v2`
- `cicero-vscode-extension`
- `cicero-template-library`
- `models`
- etc...

**Describe the solution you'd like**
This should reference contributors to the specific repository. Reference [`vue`](https://github.com/vuejs/vue):
![Screen Shot 2019-09-10 at 14 59 36 PM](https://user-images.githubusercontent.com/36460856/64642139-a91c1800-d3db-11e9-89fb-e9920f53487e.png)

**Describe alternatives you've considered**
Open to alternatives. 

**Additional context**
N/A

**Comment by irmerk** [comment]
### Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by daniloff200** [comment]
Can pick this one, I think :)

**Comment by mttrbrts** [comment]
@daniloff200 
This PR should help with this, https://github.com/accordproject/techdocs/pull/98

Also, if you're feeling more adventurous you may want to tackle this related issue too, https://github.com/accordproject/techdocs/issues/100

**Comment by sameshl** [comment]
@irmerk Would love to work on this!

**Comment by daniloff200** [comment]
Looks like it's assigned to me  already 🤔

**Comment by sameshl** [comment]
I think there are a lot of repos for which the task has to be done. So I thought maybe we could split them in between?:sweatsmile:

**Comment by mttrbrts** [comment]
We're following @kharaone's suggestion in https://github.com/accordproject/techdocs/issues/100 and have enabled the https://allcontributors.org/ bot.

Here's the current allocation:
- techdocs - @Niladri24dutta 

Why don't @sameshl and @daniloff200 share the rest between you?
- ergo - @daniloff200 
- cicero - @daniloff200 
- cicero-ui - @daniloff200 
- markdown-editor - @daniloff200 
- markdown-transform - @daniloff200 
- slate-markdown-transform - @sameshl
- template-studio-v2 - @sameshl
- cicero-vscode-extension - @sameshl
- cicero-template-library - @sameshl
- models - @sameshl

I recommend using the `all-contributors` CLI, https://allcontributors.org/docs/en/cli/usage#all-contributors-generate

**Comment by daniloff200** [comment]
Oh, I've hadn't seen, that some automatic way was already created!
Cool, thanks @mttrbrts  for info !

**Comment by irmerk** [comment]
Closed along with #100

**Comment by sameshl** [comment]
@irmerk Was this issue solved for the repos assigned to me? I was actually working on that.

**Comment by daniloff200** [comment]
@sameshl that issue was closed, because, there was a decision to leave this feature only for techdocs repo. I also made PRs with the same functionality to some repos, that were assigned to me, but, they were closed.

So, that's all.

**Comment by irmerk** [comment]
@sameshl and @daniloff200 apologies! I was a bit overambitious when wanting this in all repos, and @jeromesimeon made a good point that it would be best to keep out of source code and exist only in the docs.

**Comment by daniloff200** [comment]
no worries :) @irmerk
