### ISSUE TITLE
Markdown Transform

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#85]
## Tasks
  - Possibly add section to [this section](https://docs.accordproject.org/docs/accordproject.html#technology) for markdown
    - This would capture the tech behind Markdown Transform, Slate Transform, and Markdown Editor
    - Expand on this to describe the significance of Markdown and Concerto in AP
    - This [monorepo](https://github.com/accordproject/markdown-transform) will contain a CLI which allows people to test transforms at the command line
  - Implement screenshots

## Related Issues:
- N/A

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by susw12** [comment]
If this issue is still open, could you possibly assign it to me?

**Comment by prashi23** [comment]
Hi, Can I work on this issue?

**Comment by irmerk** [comment]
Hello @prashi23! Yes, @4katie and I are currently touching this issue a little bit. This would probably be an issue for which joining our technology working group calls (Wednesday) would be beneficial.

We are currently working on additions to [the section of docs for unstable versions][ciceromark], which will be for `v0.20-alpha`.

I think some other resources for this will be [the releases][releases] for the repo, as well as the main [README][readmelink].

[ciceromark]: https://docs.accordproject.org/docs/next/markup-commonmark.html
[releases]: https://github.com/accordproject/markdown-transform/releases
[readmelink]: https://github.com/accordproject/markdown-transform

**Comment by jeromesimeon** [comment]
The new documentation includes:
- CiceroMark guide https://docs.accordproject.org/docs/markup-cicero.html
- Markus CLI https://docs.accordproject.org/docs/markus-cli.html

I'm closing this issue as completed
