### ISSUE TITLE
Ergo (v0.20)

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#86]
## Tasks
  - **Language**
    - New string template syntax `` `This is text with {% expression %} and more text` ``
    - [Support for enumerated values, with proper typing and pattern matching support](https://github.com/accordproject/ergo/issues/3)
    - [Expression sublanguage for modifying state](https://github.com/accordproject/ergo/issues/143)
  - **Standard Librar**
    - New encode and decode functions
    - New format function for DateTime
  - **Bug fixes**
    - [`now` is no longer a magic variable](https://github.com/accordproject/ergo/issues/642)
    - [`toString` now properly format numeric values based on their types](https://github.com/accordproject/ergo/issues/575)
    - [constants are now properly imported and scoped, and can be accessed using an explicit namespace](https://github.com/accordproject/ergo/issues/465)
    - [Cicero target properly includes type hierarchy](https://github.com/accordproject/ergo/issues/644)

## Related Issues:
- #87
- [Ergo Issue 646](https://github.com/accordproject/ergo/issues/646)

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by michizhou** [comment]
I can definitely tackle this issue! Feel free to assign it to me.

**Comment by irmerk** [comment]
@michizhou We're in the middle of the Ergo `v0.20` release propagation through `alpha` to `beta` to full release. This is mainly managed and tackled by @jeromesimeon, so be sure to ask for any direction you may need.

**Comment by jeromesimeon** [comment]
The documentation now includes descriptions for:
- new built-in functions (#252 
- new "template literal" syntax(#252 
- new `state` modification statement(#252 
- an Ergo Section in the migration guide

Details of bug fixes I think are better in GitHub / Release notes.

@irmerk Can we close this?
