### ISSUE TITLE
Cicero (v0.20)

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#87]
## Tasks
  - **Dynamic Templates**
    - *need more information*
    - Gain reference material here? 
  - **Markdown Support**
    - *need more information*
    - Cicero there are changes to `generateText` to accommodate markdown support - working on the details with @jeromesimeon on this
    - Gain reference material here? 
  - **Transform diagram**
    - Markdown syntax for templates, details around this
  - **Update screenshots**

## Related Issues:
- #86
- [Cicero Issue 412](https://github.com/accordproject/cicero/issues/412)

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by michizhou** [comment]
I can definitely tackle this issue! Feel free to assign it to me.

**Comment by irmerk** [comment]
@michizhou Same comment as the Ergo issue: We're in the middle of the Cicero `v0.20` release propagation through `alpha` to `beta` to full release. This is mainly managed and tackled by @jeromesimeon, so be sure to ask for any direction you may need.

**Comment by jeromesimeon** [comment]
Somme thoughts following #147 👍 

- We should make sure to indicate that this is not normative and that the official specification is at: https://commonmark.org
- We might want to focus on markup which is most relevant to our audience (e.g., I'm not sure code blocks are relevant for us so we could mention them but maybe no need to spend much time on it?)
- We may want to focus on markup which we know we support in the markdown editor. I would check with @dselman and @irmerk about those (e.g., do we support links or cross references?).
- It might be nice to adjust the text to have legal-like examples (e.g., Clause v Heading?) -- this suggestion could be either a good idea or counter productive...

**Comment by jeromesimeon** [comment]
New documentation for Cicero 0.20 includes:
- Revisions to the CLI
- Revisions to all the getting started and user tutorials Sections
- New documentation for the CiceroMark syntax
- New template diagrams
- Migration guide, including changes to the API

@irmerk can we close this?
