### ISSUE TITLE
Concerto Links

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#90]
**Describe the bug**
Documentation links to `concerto` still refer to Hyperledger's repositories

**To Reproduce**
The highlighted line here has an incorrect link:
<img width="1380" alt="Screen Shot 2019-09-18 at 16 25 31 PM" src="https://user-images.githubusercontent.com/36460856/65183489-959f2b80-da31-11e9-9473-6d3b6de204f3.png">

**Expected behavior**
Correct these links to https://github.com/accordproject/concerto

**Additional context**
There may be further broken links, search through the docs

**Comment by aayushbisen** [comment]
I like to work on this issue. 🙂

**Comment by daniloff200** [comment]
Please, assign this to me : ) 
also, if I found some other broken links (not related to exactly this case ), can I ask here, what's the expected behaviour?

**Comment by irmerk** [comment]
@daniloff200: I think the best option would be raising another issue. If it's a duplicate, we can either reference it or close it in favor for an existing one.
