### ISSUE TITLE
Concerto Docs

### ISSUE THREAD

**Issue by irmerk** [accordproject/techdocs#91]
## Tasks
  - Possibly adapt [this section](https://docs.accordproject.org/docs/accordproject.html#concerto) for concerto, now being a part of accordproject and not hyperledger
    - Could include further information in other locations of the docs

## Related Issues:
- N/A

## Hacktoberfest:
This issue can provide for multiple pull requests.

**Comment by michizhou** [comment]
I can definitely tackle this issue! Feel free to assign it to me.

**Comment by jeromesimeon** [comment]
Some of the existing material that we can borrow from include:
- Modeling Reference from HL Composer: https://hyperledger.github.io/composer/latest/reference/cto_language.html
- The READMEs in this very project

Whatever we write should be consistent with the nice intro by @dselman at: https://www.accordproject.org/news/strongly-typed-data-for-javascript-and-beyond/

**Comment by irmerk** [comment]
Opening back up after 20 days stale.
