### ISSUE TITLE
LF logo missing

### ISSUE THREAD

**Issue by peterhunn** [accordproject/techdocs#92]
Linux Foundation logo is missing in the footer of the Technical docs (cf. www.accordproject.org)

**Comment by Michael-Grover** [comment]
![image](https://user-images.githubusercontent.com/40569793/65192073-f46da080-da43-11e9-82cd-650f91da3d4d.png)

Whoever tackles this issue, see accordproject.org's footer for reference on how the linux foundation logo should appear. Have the logo appear like this on all tech doc subsites of the Accord Project such as https://docs.accordproject.org/  and https://models.accordproject.org/

**Comment by Michael-Grover** [comment]
@jeromesimeon I think you are most familiar with the how the techdoc pages are set up, right?

**Comment by oorjitchowdhary** [comment]
can i take this up?

**Comment by Michael-Grover** [comment]
@oorjitchowdhary 

Here is the image asset.

![linux-foundation](https://user-images.githubusercontent.com/40569793/65970236-1f88c480-e434-11e9-98a9-db0290e90f68.png)

The width should be 300px, with 50px margin on top and bottom.

It should hyperlink to this URL as it does on the Accord Project website: https://www.linuxfoundation.org/projects/

The logo needs to appear in the footers of these sites. I marked in red where the logo should be for each site.

docs.accordproject.org

![image](https://user-images.githubusercontent.com/40569793/65970501-b190cd00-e434-11e9-9245-e9c20c78ef9c.png)

models.accordproject.org
![image](https://user-images.githubusercontent.com/40569793/65970562-cbcaab00-e434-11e9-87c2-1e259cf567a2.png)

templates.accordproject.org
![image](https://user-images.githubusercontent.com/40569793/65970620-e69d1f80-e434-11e9-9348-12be78a658cc.png)

**Comment by VishalS99** [comment]
Can I take this problem? I think I can get it done quickly!

**Comment by Michael-Grover** [comment]
@VishalS99 yes, thank you!

**Comment by Michael-Grover** [comment]
Which of the two PRs adds the logo on models.accordproject.org and templates.accordproject.org?

**Comment by VishalS99** [comment]
Well I kept it separate, as they were separate repos. This pr is for docs and the other one is templates

**Comment by Michael-Grover** [comment]
I don't see the logo on models.accordproject.org and templates.accordproject.org yet. @jeromesimeon does this mean it hasn't deployed yet? @VishalS99 thanks for the clarification. excuse my silly questions, I'm not a dev.

**Comment by VishalS99** [comment]
Cool no probs :)

**Comment by jeromesimeon** [comment]
@Michael-Grover What @VishalS99 said. I haven't looked at the PRs on the other repos yet.

**Comment by VishalS99** [comment]
I have also fixed it for models.accordproject.org. I could give a PR for the repo too. Is it fine @jeromesimeon ?

**Comment by jeromesimeon** [comment]
Sure sounds good @VishalS99 Could you please post links here to that @Michael-Grover can comment/review? thanks.

**Comment by VishalS99** [comment]
Cool!!

**Comment by VishalS99** [comment]
https://github.com/accordproject/cicero-template-library/pull/275#issue-327252612

**Comment by VishalS99** [comment]
https://github.com/accordproject/cicero-template-library/pull/275 this is the pr for  template site

**Comment by VishalS99** [comment]
and https://github.com/accordproject/models/pull/68#issue-327309885 this PR is for model site

**Comment by VishalS99** [comment]
I guess I have taken care of all the requirements for this issue.

**Comment by VishalS99** [comment]
@Michael-Grover or @jeromesimeon could check it out? Thanks.

**Comment by jeromesimeon** [comment]
Completed and merged for `docs` `templates` and `models`. Thanks for the contributions @VishalS99 ! I'm closing this issue.

**Comment by Michael-Grover** [comment]
@VishalS99 this looks great, thanks again!

**Comment by jeromesimeon** [comment]
This seems broken everywhere, except for the main page? e.g., https://docs.accordproject.org/docs/accordproject.html

![Uploading Screenshot 2019-10-19 at 2.24.53 PM.png…]()

**Comment by VishalS99** [comment]
I'll get it fixed asap

**Comment by VishalS99** [comment]
I guess it's a path issue

**Comment by jeromesimeon** [comment]
> I guess it's a path issue

@VishalS99 Most likely! I am not sure how we missed it in the initial PR, but if you could look at it that would be great!

**Comment by VishalS99** [comment]
It was working initially, don't know how it changed

**Comment by VishalS99** [comment]
Here is the update. The image path was wrong.
Do check and update!
