### ISSUE TITLE
AP logo in footer

### ISSUE THREAD

**Issue by peterhunn** [accordproject/techdocs#93]
**Describe the bug**
AP logo in the footer is dulled on rollover: 
![image](https://user-images.githubusercontent.com/9304034/65192103-a6ed3580-da3b-11e9-8716-76a4acac2aff.png)

Should be consistent with www.accordproject.org.

**Comment by daniloff200** [comment]
hi, @peterhunn 
Do you mean the  hover effect ?
Because, on www.accordproject.org there are no  dark colors on hover, only the cursor. Should I change it ?

**Comment by daniloff200** [comment]
If so, feel free to assign this to me, and also, you can add a Hacktoberfest label for it :jack_o_lantern:

**Comment by irmerk** [comment]
Ah, yes this was in reference to the footer here: https://docs.accordproject.org/

**Comment by sesam** [comment]
Labeling for this is not updated - looks like it's both Taken and soon completed! :tada:

**Comment by irmerk** [comment]
> Labeling for this is not updated - looks like it's both Taken and soon completed! 🎉

Unsure what you mean. It's taken and soon completed, so I think the labeling is up to date.

**Comment by sesam** [comment]
Sorry - just meant that other issues were tagged with "Good first issue (taken)" which maybe doesn't apply. But I did a good effort to find something interesting to dip my toes here :)

**Comment by irmerk** [comment]
> Sorry - just meant that other issues were tagged with "Good first issue (taken)" which maybe doesn't apply. But I did a good effort to find something interesting to dip my toes here :)

It isn't the best system, but assigning it to someone means it is taken, but the `Good First Issue (Taken)` is just a contrast to the commonplace `Good First Issue`.
